apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-init-container
spec:
  initContainers:
    - name: my-init-container
      image: busybox:latest
      command: ["sleep"]
      args: ["15"]
  containers:
    - name: nginx-container
      image: nginx:latest
